services:
  - type: web
    name: wizardgame
    runtime: node
    plan: free
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: SESSION_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        sync: false
